const DATA={"exercises": {"strength": [["Sentadilla en silla", "10–12 repeticiones", "squat", "Colócate frente a una silla estable. Lleva la cadera atrás, baja con control y vuelve a subir.", "Exhala al subir."], ["Elevación de brazos con banda", "10 por lado", "arms", "Eleva un brazo lentamente con banda o peso ligero, sin encoger los hombros.", "Exhala al elevar."], ["Puente de glúteos", "10 repeticiones", "bridge", "Boca arriba, rodillas flexionadas. Eleva la cadera y baja lentamente.", "Exhala al elevar."], ["Elevación de talones", "15 repeticiones", "heels", "De pie junto a una silla, eleva ambos talones y desciende con control.", "Respira continuamente."], ["Remo sentada con banda", "10 repeticiones", "row", "Sentada erguida, lleva los codos hacia atrás y regresa lentamente.", "Exhala al tirar."]], "balance": [["Apoyo en un pie", "20–30 s por lado", "oneleg", "Junto a una silla, eleva un pie y mantén la postura sin bloquear la rodilla.", "Respira con normalidad."], ["Caminata talón-punta", "10 pasos", "tandem", "Camina en línea colocando el talón justo delante de la punta del otro pie.", "Mira al frente y respira."], ["Círculos de tobillo y cadera", "10 por lado", "circles", "Con apoyo cercano, realiza círculos lentos y cómodos, sin forzar.", "Movimiento suave."], ["Flamenco modificado", "15–20 s por lado", "flamingo", "Apoya una mano en la silla y eleva una pierna flexionada de forma cómoda.", "Respira continuamente."]], "yoga": [["Cuello y hombros", "30 s por lado", "neck", "Inclina suavemente la cabeza hacia un lado y relaja los hombros.", "Sin rebotes."], ["Gato-vaca", "8–10 repeticiones", "catcow", "En cuatro apoyos, alterna suavemente entre redondear y extender la espalda.", "Coordina movimiento y respiración."], ["Postura del niño", "30–60 s", "child", "Lleva la cadera hacia los talones de forma cómoda, sin bajar la cabeza bruscamente.", "Respira lento."], ["Torsión suave sentada", "20 s por lado", "twist", "Sentada, gira el tronco suavemente sujetando la silla.", "No fuerces el giro."], ["Respiración diafragmática", "5–8 repeticiones", "breath", "Coloca una mano sobre el abdomen y deja que se eleve al inhalar.", "Exhala lentamente."]], "cardio": [["Caminata en el sitio", "3–5 min", "march", "Marcha a ritmo cómodo elevando alternadamente los pies.", "Debes poder hablar."], ["Step lateral", "3–5 min", "sidestep", "Da pasos laterales controlados a derecha e izquierda.", "Mantén un ritmo cómodo."], ["Bicicleta estática", "5–8 min", "bike", "Pedalea con resistencia ligera y postura cómoda.", "No contengas la respiración."], ["Baile suave", "3–5 min", "dance", "Muévete libremente con pasos sencillos y controlados.", "Mantén intensidad ligera."]]}, "meta": {"strength": ["Fuerza suave", "20 min", "Nivel bajo", "🪑"], "balance": ["Equilibrio y estabilidad", "12 min", "Nivel bajo-medio", "⚖️"], "yoga": ["Flexibilidad y relajación", "18 min", "Nivel bajo", "🌿"], "cardio": ["Cardio ligero", "18 min", "Nivel bajo-medio", "♥"]}};

let S={route:"routines",cat:null,i:0,bp:JSON.parse(localStorage.getItem("bp")||"[]"),done:+localStorage.getItem("done")||0};
const V=document.querySelector("#view");
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>go(b.dataset.r));
aa.onclick=()=>document.documentElement.classList.toggle("big");
function go(r){S.route=r;S.cat=null;render();scrollTo(0,0)}
function avatar(cls){return `<div class="avatar-stage ${cls}"><div class="shadow"></div><div class="human"><div class="hair"></div><div class="head"></div><div class="body3"></div><div class="arm al"></div><div class="arm ar"></div><div class="leg ll"></div><div class="leg lr"></div><div class="shoe sl"></div><div class="shoe sr"></div></div></div>`}
function routines(){return `<h1>Rutinas</h1>`+Object.entries(DATA.meta).map(([k,m])=>`<div class="card routine"><div class="ico">${m[3]}</div><div class="body"><h2>${m[0]}</h2><div class="tags">${m[1]} · ${m[2]}</div><button class="btn secondary" onclick="openCat('${k}')">Ver rutina</button></div></div>`).join("")}
function openCat(k){S.cat=k;S.i=0;S.route="exercise";render();scrollTo(0,0)}
function exercise(){let a=DATA.exercises[S.cat],e=a[S.i],m=DATA.meta[S.cat];return `<div class="muted">${m[0].toUpperCase()}</div><div style="display:flex;justify-content:space-between;align-items:center"><h1 style="margin-bottom:8px">${e[0]}</h1><b>${S.i+1}/${a.length}</b></div><div class="progress"><i style="width:${(S.i+1)/a.length*100}%"></i></div>${avatar(e[2])}<div class="card"><div class="muted">OBJETIVO</div><h1>${e[1]}</h1><h2>Cómo hacerlo</h2><p>${e[3]}</p><div class="notice"><b>Respira</b><br>${e[4]}</div><div class="notice warning">Detente si aparece mareo, dolor en el pecho o falta de aire inusual. Mantente hidratada.</div><div class="field"><button class="btn secondary" onclick="prev()">← Anterior</button><button class="btn" onclick="next()">${S.i===a.length-1?"Finalizar ✓":"Siguiente →"}</button></div></div>`}
function prev(){if(S.i>0){S.i--;render();scrollTo(0,0)}else go("routines")}
function next(){let a=DATA.exercises[S.cat];if(S.i<a.length-1){S.i++;render();scrollTo(0,0)}else{S.done++;localStorage.setItem("done",S.done);S.route="finish";render()}}
function home(){return `<div class="card hero"><h1>Tu movimiento de hoy</h1><p>Elige una rutina cómoda y avanza a tu ritmo.</p><button class="btn" onclick="go('routines')">Ver las 4 rutinas</button></div><div class="card"><h2>Rutinas completadas</h2><h1>${S.done}</h1></div>`}
function health(){let last=S.bp.at(-1);return `<h1>Mi salud</h1><div class="card"><h2>Registrar presión arterial</h2><div class="field"><input id="sys" inputmode="numeric" placeholder="Sistólica"><input id="dia" inputmode="numeric" placeholder="Diastólica"></div><button class="btn" style="margin-top:14px" onclick="saveBP()">Guardar</button><div id="msg"></div></div><div class="card"><h2>Última lectura</h2><h1>${last?last.s+"/"+last.d:"— / —"}</h1><span class="muted">mmHg</span></div>`}
function saveBP(){let s=+sys.value,d=+dia.value;if(!s||!d)return;S.bp.push({s,d,t:Date.now()});localStorage.setItem("bp",JSON.stringify(S.bp));msg.innerHTML=(s>180||d>120)?`<div class="notice danger"><b>Lectura muy alta.</b><br>No inicies ejercicio. Descansa al menos 1 minuto y repite la medición. Si continúa por encima de 180/120, contacta de inmediato a un profesional de salud. Con dolor de pecho, falta de aire, debilidad, cambios de visión o dificultad para hablar, busca atención de emergencia.</div>`:`<div class="notice">Registro guardado.</div>`}
function progress(){return `<h1>Progreso</h1><div class="card"><h2>Rutinas completadas</h2><h1>${S.done}</h1><p class="muted">La constancia importa más que la velocidad.</p></div>`}
function finish(){return `<div class="card hero"><h1>¡Rutina completada! 🌷</h1><p>Muy bien. Recupera la respiración poco a poco y toma agua.</p><button class="btn" onclick="go('routines')">Elegir otra rutina</button></div>`}
function render(){V.innerHTML=S.route==="routines"?routines():S.route==="exercise"?exercise():S.route==="health"?health():S.route==="progress"?progress():S.route==="finish"?finish():home()}
render();
